### ISSUE TITLE
OnePlus 7 Pro (Crdroid A13 rom)

### ISSUE THREAD

**Issue by Bartixxx32** [anonymix007/ExtA2DP#1]
Hello, first of all i understand that this module is new and  untested on other devices and roms, but i tried to install it becouse i like to have back lhdc codec on custom rom for my OnePlus Buds Pro 2 that supports that.

After install of lsposed version from your requirment, installed magisk module and lsposed module, but can not open developer settings, becouse its crashing, i grabbed crashlog, maybe would you like to have a look?

https://paste.crdroid.net/vd5FEs

I hope at some day other phones also could have lhdc support back via your module! Thanks

![Screenshot_20230718-114432_ExtA2DP.png](https://github.com/anonymix007/ExtA2DP/assets/16412925/c731ee0e-0590-4165-a38d-cfd7f6d0b1a1)

**Comment by anonymix007** [comment]
Run `getpropro.bluetooth.library_name` in adb shell or termux. What it outputs?

**Comment by Bartixxx32** [comment]
Sadly no output in termux, seems this prop is not used?

![Screenshot_20230718-125150_Termux.png](https://github.com/anonymix007/ExtA2DP/assets/16412925/fca04fff-a02e-473e-9fff-3feb7e3e74e8)

**Comment by anonymix007** [comment]
Does the `/system_ext/lib64/libbluetooth_qti.so` file exist?

**Comment by Bartixxx32** [comment]
looks like its not exist

**Comment by Bartixxx32** [comment]
Some logs: 

[LSPosed_2023-07-18T12_57_36.790278.zip](https://github.com/anonymix007/ExtA2DP/files/12079629/LSPosed_2023-07-18T12_57_36.790278.zip)
[magisk_log_2023-07-18T12.57.19.log](https://github.com/anonymix007/ExtA2DP/files/12079630/magisk_log_2023-07-18T12.57.19.log)

**Comment by Bartixxx32** [comment]
Files with libbluetoith in name

![Screenshot_20230718-130422_Termux.png](https://github.com/anonymix007/ExtA2DP/assets/16412925/3d409066-e6e7-4a64-baf5-76bc1df59be1)

**Comment by anonymix007** [comment]
That means crDroid is not based on CLO and will never be supported by this module. 
You can wait for LHDC to be merged into Paranoid Android, build it by yourself with [repopick](https://gerrit.aospa.co/q/lhdc) or try this module there.

**Comment by Bartixxx32** [comment]
oh, ok then, anyways thanks for help :)

**Comment by Bartixxx32** [comment]
> That means crDroid is not based on CLO and will never be supported by this module. You can wait for LHDC to be merged into Paranoid Android, build it by yourself with [repopick](https://gerrit.aospa.co/q/lhdc) or try this module there.

whih module?

**Comment by anonymix007** [comment]
I've looked at the source code of PA during the development a lot (even `libbluetooth_exta2dp.so` is built from PA tree), so ExtA2DP has high chances of being compatible with PA.

**Comment by Bartixxx32** [comment]
Thanks for your time, but for now i`m gonna stick with crdroid, but will try repopick and try to rebuild rom with this patch and see :P 
![image](https://github.com/anonymix007/ExtA2DP/assets/16412925/0037e1a5-0473-4360-9a7e-12d026ceef1e)

**Comment by Bartixxx32** [comment]
> That means crDroid is not based on CLO and will never be supported by this module. You can wait for LHDC to be merged into Paranoid Android, build it by yourself with [repopick](https://gerrit.aospa.co/q/lhdc) or try this module there.

i still wonder what module had you on mind when sayying ```or try this module there``` can you explain?

**Comment by anonymix007** [comment]
[This one](https://github.com/anonymix007/ExtA2DP).

**Comment by Bartixxx32** [comment]
oh, haha arleady tried thats why i`m in issues tab here :P

**Comment by anonymix007** [comment]
There == in PA

**Comment by Bartixxx32** [comment]
oh, thats make more sense now, ok thanks, im not taking your time anymore :D
