### ISSUE TITLE
Xiaomi Poco F5 (marble) - LHDC no sound

### ISSUE THREAD

**Issue by firengate** [anonymix007/ExtA2DP#10]
Hello!

Xiaomi Poco F5 (marble)
Paranoid Topaz Stable 1 A13
Headphones - OnePlus Buds Pro 2R

Installed LSPosed v1.9.2 (7045) + audio_policy_changer_magisk.zip in Magisk 26.4.
ExtA2DP module is enabled in LSPosed Manager.
The device is rebooted.
Choice of additional codecs appeared and I chose LHDC.

There is no sound in the headphones.
There are many messages in logcate during audio playback: LHDC not enabled in offload currently.
Tried turning A2DP hardware offloading on and off and rebooting the smartphone, still no sound.

I collected all the logs, libraries, and bluetooth app.
Logs were recorded according to the instructions.

Your mod is the only hope in all custom firmware to get LHDC.
Thank you so much for your work.

![Screenshot_20231214-090023_Kitsune_Mask](https://github.com/anonymix007/ExtA2DP/assets/25734655/030a95ec-8b35-47eb-925c-dc090375b8c2)
![Screenshot_20231214-091515](https://github.com/anonymix007/ExtA2DP/assets/25734655/c2555e0e-956f-4d23-8fa4-8db8004e4b2f)
![Screenshot_20231214-091532_Оболочка](https://github.com/anonymix007/ExtA2DP/assets/25734655/ec8886e5-9dd0-44ff-9790-5593699a9207)
![Screenshot_20231214-091821_App_Manager](https://github.com/anonymix007/ExtA2DP/assets/25734655/e26659e2-e99c-4692-9b3a-a750c8e6f100)
![Screenshot_20231214-091928_ExtA2DP](https://github.com/anonymix007/ExtA2DP/assets/25734655/eb9634fd-e3f1-4501-96d9-65b4d0c51438)
![Screenshot_20231214-091939_ExtA2DP](https://github.com/anonymix007/ExtA2DP/assets/25734655/558b9800-7182-4ee4-86fa-8ab0c8676dcf)
![Screenshot_20231214-092017_Настройки](https://github.com/anonymix007/ExtA2DP/assets/25734655/6d50e413-5f98-482c-8126-ac9f107672b3)

apk + libs
https://dropmefiles.com/4pQjv

logcat
https://dropmefiles.com/i3BWB

lsposed logs
https://dropmefiles.com/otGNP

**Comment by anonymix007** [comment]
К сожалению, это известная проблема на всех относительно свежих Xiaomi. По неизвестной причине у них всех `is_aidl_hal_available == 0` и,предположительно, из-за этого они пытаются запустить HW Offload (причём вообще AAC) несмотря на A2DP_SOFTWARE_ENCODING_DATAPATH.
Можно попробовать временно отключить A2DP HW Offload.

**Comment by anonymix007** [comment]
> У меня в данный момент выключен A2DP HW Offload в меню разработчика.

Пункт в меню разработчика называется "Disable Bluetooth A2DP hardware offload". Если он выключен (а по умолчанию это так), то A2DP HW Offload включён. И вывод getprop это подтверждает:
`[persist.bluetooth.a2dp_offload.disabled]: [false]`
Не выключено == включено.

**Comment by anonymix007** [comment]
> В приложении ExtA2DP показано, что протокол используется LLAC, потом я вручную в приложении ставлю битрейт 500 кбит и протокол меняется на LHDC v4

Это нормально, LLAC - один из вариантов LHDC 3, как и 4. Один из них выбирается автоматически по достаточно сложным правилам в зависимости от битрейта и частоты дискретизации. На 2R ещё должен быть 5, что с ним?
> звук начинает идти через динамик телефона

Это баг прошивки

А если в одном из этих сценариев запустить `sudo setprop ctl.restart audioserver`?
И отдельно можно проверить [эту версию](https://github.com/anonymix007/ExtA2DP/files/13672742/app-debug.zip).

**Comment by anonymix007** [comment]
Тогда прямой путь к мейнтейнеру, прямо как и в #9. Нужно включить AOSP AIDL HAL и починить выключенный offload.
Был успешный случай запуска LHDC V5 на F5 с [этим](https://github.com/anonymix007/ExtA2DP/files/13674883/apl_marble.zip) модулем и, насколько я помню, версией 2.2.3, хотя вряд ли что-то поменяется и в последней.

**Comment by anonymix007** [comment]
Да, это оно, скорее всего.
