### ISSUE TITLE
Redmi Note 11 (spes) Topaz [No BT)

### ISSUE THREAD

**Issue by LeRatGondin** [anonymix007/ExtA2DP#12]
Thanks for your module , I have a xiaomi redmi spes .I've installed this module with lsposedon my PA ROM and the bluetooth won't enable . Here's the log.Can you help me ?
[logs.txt](https://github.com/anonymix007/ExtA2DP/files/13762677/logs.txt)

**Comment by LeRatGondin** [comment]
Thanks for your build , swiping the codec does work but the LHDC audio is played throught the audio speaker and not the earbuds.
Sorry to bother you and thanks for your project.

**Comment by anonymix007** [comment]
You will need a different Magisk companion module. Refer to those provided in other issues. You will need to change audio policy configuration xml in the main companion module.

**Comment by LeRatGondin** [comment]
thanks for your help
