### ISSUE TITLE
Poco F3 (Paranoid CAF A14)

### ISSUE THREAD

**Issue by kennyeazy** [anonymix007/ExtA2DP#14]
Привет, установлен полный набор для LHDC, в итоге не появляется пункт в приложении, где можно выбрать этот кодек, с чем это связано? Может лог нужен?

**Comment by anonymix007** [comment]
> There will be a separate version for 14 due to incompatibility.

**Comment by kennyeazy** [comment]
> > There will be a separate version for 14 due to incompatibility.

Понял, спасибо, могу ли чем-то помочь скорее выпустить модуль?

**Comment by anonymix007** [comment]
Нет. У меня до сих пор 13, а обнову до 14 обещали в феврале-марте.
