### ISSUE TITLE
android14 support

### ISSUE THREAD

**Issue by M1sterXXL** [anonymix007/ExtA2DP#16]
![Screenshot_20240214-114954](https://github.com/anonymix007/ExtA2DP/assets/89202894/6cec6def-e2da-4fef-a20b-3635969d09fb)
im using a14 is that normal? because the module does not support a14, i think

**Comment by anonymix007** [comment]
Module app should work even without root for some use-cases (as `Bluetooth Codec Changer` replacement), but you'll need to connect to the device first to change codecs and their parameters.
But yeah, LSPosed part will not work on A14 (as well as on A12 and actually for the same reason), so no LHDC etc until version for A14 will be released.
