### ISSUE TITLE
v3.0.0 Android 14 not working

### ISSUE THREAD

**Issue by VincAlastor** [anonymix007/ExtA2DP#18]
thanks for your v3.0.0 release. I tried to get the version running over the weekend. Unfortunately without success. Here is my system:

Xiaomi Mi 11i/haydn (SD 888)
crDroidAndroid-14.0-20240210-haydn-v10.2
FW V14.0.7.0.TKKEUXM
AGNi_kernel-haydn-stable-v5.8-AOSP-ST
latest KernelSU
Zygisk Next 1.0.1
LSPosed-v1.9.2-7058-zygisk-debug

When I open the ExtA2DP, the following notification appears:

![grafik](https://github.com/anonymix007/ExtA2DP/assets/24430747/88484635-3a09-4370-868c-246ec8b02362)

In the dev options the new Bluetooth codecs are listed, but not used when reconnecting with LHDC v4 headphones. I would be happy if you can find the error in the attached log.

**Comment by anonymix007** [comment]
crDroid is explicitly not supported. You will need CLO ROM for this. Even though it's a bit easier to support non-CLO ROMs after v3.0.0, I still don't have plans for that. Even though I might do it, I don't really want to support these shitty ROMs which are using AOSP BT stack on devices with Qualcomm SoCs.

**Comment by VincAlastor** [comment]
Thank you for taking a look. With a not very prominent device, you have limited ROM choices. Your module was one of a few chances. You are one of very few devs who even recognize and perceive this Android Bluetooth audio codec issue. And yes, it's really not nice to be limited to max. AAC and for whatever reason max. 44.1 KHz with crdroid at the moment. Especially the downsample to 44.1 KHz sounds terrible.

**Comment by anonymix007** [comment]
Well, I will continue improving compatibility with non-CLO ROMs in the future. What currently the issue is that ExtA2DP fails to load it's Bluetooth stack replacement library (apart from a few missing classes in AOSP BT, which could be just ignored if missing). This is what I'd expect it to do with a non-CLO ROM. But we already have an open issue for that: #13 
There certainly needs to be a separate cut-down version for these. I might try building one later.

**Comment by VincAlastor** [comment]
Thank you again for your attention to this important topic. I have now ordered LC3plus headphones. I have seen that you have committed the liblc3 on github. Do you know if this lib is automatically updated on google and AOSP so that lineage/crdroid also get the LC3plus features? Can I somehow check which lib version is in the following ROM?

https://sourceforge.net/projects/crdroid/files/haydn/10.x/crDroidAndroid-14.0-20240407-haydn-v10.4.zip/download

Sorry, this is pretty off topic, but I don't know who is closer to the topic than you.

**Comment by anonymix007** [comment]
> Can I somehow check which lib version is in the following ROM?

There doesn't seem to be a direct way to check the version, but you may try to unpack it, find btservices apex, extract it and use `strings` on `libbluetooth_jni.so` to find liblc3 functions.
> Do you know if this lib is automatically updated on google and AOSP so that lineage/crdroid also get the LC3plus features?

Of course it is not. The [main](https://android.googlesource.com/platform/external/liblc3/+/refs/heads/main) branch doesn't have v1.1.0 tag merged. And even if it did, AOSP is not using these features nor there are any plans to do so.
