### ISSUE TITLE
OnePlus 7T Pro (Parandroid Topaz 7 A13 rom)

### ISSUE THREAD

**Issue by borz7zy** [anonymix007/ExtA2DP#21]
Hi! I will immediately describe the problem, OnePlus 7t pro and OnePlus buds pro 2. Headphones are connected, there is a codec, but the system cannot switch to it. When using LHDC 5, the sound plays in the speakers of the phone, when using LHDC 3, there is no sound. I'm attaching logs!
Paranoid android 13 r7 firmware, module version 2.3.0, lsposed version 1.9.2 (7945) debug.
When trying to use the OnePlus 7 pro module from a similar theme - bluetooth does not work when the system boots!. ( [here](https://github.com/anonymix007/ExtA2DP/issues/2#issuecomment-1646835100) )
[logs.txt](https://github.com/anonymix007/ExtA2DP/files/15287951/logs.txt)

![Screenshot_20240513-010108](https://github.com/anonymix007/ExtA2DP/assets/66177661/79771d3c-c960-4dd1-897d-6bd0aa9465aa)
![Screenshot_20240513-010116](https://github.com/anonymix007/ExtA2DP/assets/66177661/024fd6e7-9956-4864-8411-5b5b90c5e6a5)
![Screenshot_20240513-010142](https://github.com/anonymix007/ExtA2DP/assets/66177661/689d2faa-816a-46ce-b69d-ea9cdc9bf0ac)

**Comment by anonymix007** [comment]
~~AFAIR [this one](https://github.com/anonymix007/ExtA2DP/files/15291409/module.zip) was confirmed to be working on 1+7 Pro.~~

Only worked for an older versions.

**Comment by borz7zy** [comment]
After installing this module, bluetooth does not start, and the Bluetooth application crashes. I removed the logs when I tried to turn on bluetooth. I also filmed the behavior.
[video](https://www.youtube.com/shorts/eGvq1aRjC08)
[logs2.txt](https://github.com/anonymix007/ExtA2DP/files/15291820/logs2.txt)
![Screenshot_20240513-104101](https://github.com/anonymix007/ExtA2DP/assets/66177661/82518149-0147-4012-8774-b79f96cb8d8f)

**Comment by anonymix007** [comment]
Редактировать было необязательно, я и так понял.

А с [module.zip](https://github.com/anonymix007/ExtA2DP/files/15292081/module.zip) заработает?

**Comment by borz7zy** [comment]
bluetooth начинает работать, но с наушниками все те же беды - lhdc 5 сразу выводит на динамик, переключение на lhdc 3 дает эффект что система либо выводит на динамики, либо просто нет звука.
[logs3.txt](https://github.com/anonymix007/ExtA2DP/files/15292201/logs3.txt)

**Comment by anonymix007** [comment]
Загрузите сюда `audio_policy_configuration.xml` (должен быть где-то в `/vendor/etc/audio`) и `/vendor/etc/bluetooth_hearing_aid_audio_policy_configuration.xml`

**Comment by borz7zy** [comment]
[bluetooth_hearing_aid_audio_policy_configuration.xml](https://drive.google.com/file/d/1tGODb7EjT56GxoKic1MJ7nPxqenAL_SB/view?usp=sharing)

[audio_policy_configuration.xml](https://drive.google.com/file/d/18DmfELDIWGuRcXDhL5wmU8n_AjWJdPde/view?usp=drive_link)

**Comment by anonymix007** [comment]
Нужно сначала модуль отключить или из самой прошивки (`vendor.img`) извлекать.

**Comment by borz7zy** [comment]
[bluetooth_hearing_aid_audio_policy_configuration.xml](https://drive.google.com/file/d/139I1HDco6jPt21RcEvydhITOH_QW81_I/view?usp=sharing)

[audio_policy_configuration.xml](https://drive.google.com/file/d/1WfyTP4h2G2Rf89OjnDWNV3sRL6s0qhaE/view?usp=sharing)

**Comment by anonymix007** [comment]
А есть логи с самой перезагрузки?

**Comment by anonymix007** [comment]
И заодно сразу с [module.zip](https://github.com/anonymix007/ExtA2DP/files/15292614/module.zip)

**Comment by borz7zy** [comment]
Заработало с этим модулем, благодарю!
Логи ещё нужны?

**Comment by anonymix007** [comment]
Нет, заработало же.
