### ISSUE TITLE
Poco F5 can't turn on Bluetooth(Fork of Paranoid Android)

### ISSUE THREAD

**Issue by DyingRocket55** [anonymix007/ExtA2DP#22]
Can't turn on Bluetooth after installing Exta2dp. My previously connected devices also don't show. The problem is fixed if I disable the module.

**Comment by DyingRocket55** [comment]
Nvm. I saw the thread with the same issue.
Waiting for the update 🙏

**Comment by anonymix007** [comment]
Duplicate of #20 
If you don't mind, I'll tag you there once I upload a test build.
