### ISSUE TITLE
OnePlus 7TPro | Project Martixx V10.8.0 (A14)

### ISSUE THREAD

**Issue by borz7zy** [anonymix007/ExtA2DP#24]
Здравствуйте!
В прошлый раз уже обращался с данным аппаратом на другой прошивке (https://github.com/anonymix007/ExtA2DP/issues/21).
Теперь же переехал на другую прошивке с android 14 (Project Martixx V10.8.0), и появилась проблема, ни модуль из релиза, ни модуль из нашего прошлого issue не работает.
Сразу прикрепляю логи (модуль из релиза), а так же файлы с системы.

[logs.txt](https://github.com/user-attachments/files/17019694/logs.txt)
[audio_policy_configuration.xml](https://drive.google.com/file/d/1ebRg8SaBxM_wtl3xm_-gIR5isSmNbck2/view?usp=sharing)
[bluetooth_audio_policy_configuration.xml](https://drive.google.com/file/d/1ujTtj3SVe70csv3uqSKqJskGzkDG3Jf2/view?usp=sharing)

**Comment by anonymix007** [comment]
> Project Matrixx
> A sleek and intuitive custom ROM, seamlessly built upon crDroid

> crDroid is a customized fork of Android based on LineageOS.

Поддержки AOSP прошивок всё ещё нет. Возможно, поработаю над этим после версии для Android 15. Как раз начиная с этой версии в CLO тоже используется `packages/modules/Bluetooth`, так что потребуется меньше изменений для AOSP версии.
