### ISSUE TITLE
Pixel , Mi 9T

### ISSUE THREAD

**Issue by chocko13** [anonymix007/ExtA2DP#3]
pixel 6 pro, stock rom, put everything right, but it only shows a list of codecs and you can't choose from.
Mi 9T, A13, RiceDroid exactly the same problem Ok, I can understand why it may not work on my Pixel, but I thought that on Mi 9t it would work properly

I would be very happy to enable the codec for good sound on one of these devices, can you help me, I would be grateful
![Screenshot_20230820-045601](https://github.com/anonymix007/ExtA2DP/assets/55274286/f500faf9-32da-4bbf-8cee-db359ca45c3f)

**Comment by anonymix007** [comment]
> RiceDroid
