### ISSUE TITLE
Mi 9T , xperience (CAF)

### ISSUE THREAD

**Issue by chocko13** [anonymix007/ExtA2DP#4]
I realized that on my Pixel this is not yet possible And I decided to take care of my Mi 9t.
I found CAF firmware and installed everything. Now I have a different problem, the sound only plays from the speaker, like the user above. I understand that I also need a separate module for my device?
![Screenshot_20230820-140421_Magisk](https://github.com/anonymix007/ExtA2DP/assets/55274286/e63f6623-73e3-4cd5-b597-e0ba9962ec3c)
![Screenshot_20230820-140427_Bluetooth_Codec_Changer](https://github.com/anonymix007/ExtA2DP/assets/55274286/4c4b3e5b-fa57-4019-858e-f441343d9068)
![Screenshot_20230820-140439_Shell](https://github.com/anonymix007/ExtA2DP/assets/55274286/2d38c4bd-7908-44f3-955e-c9b54bf27c3e)
![Screenshot_20230820-140441_Shell](https://github.com/anonymix007/ExtA2DP/assets/55274286/2c437c36-dad3-4b31-bdb8-001e37148579)
![Screenshot_20230820-140653_Settings](https://github.com/anonymix007/ExtA2DP/assets/55274286/e1d6293f-47f8-45b9-ab74-b7f61ce977e9)
![Screenshot_20230820-141133_Files_by_Google](https://github.com/anonymix007/ExtA2DP/assets/55274286/95bf7a31-71d5-4d36-944f-53095a4221ec)

**Comment by anonymix007** [comment]
[audio_policy_mi9t.zip](https://github.com/anonymix007/ExtA2DP/files/12447842/audio_policy_mi9t.zip)
