### ISSUE TITLE
Xiaomi Mi 10T AOSPA Topaz doesn't work 

### ISSUE THREAD

**Issue by matthew777777** [anonymix007/ExtA2DP#6]
Shalom,
I tried to use every module for magisk but it doesn't work and I'm using CLO based ROM AOSPA Topaz on Mi 10T with SD865.

Can you help ? 
Shalom shalom

**Comment by anonymix007** [comment]
[mi10t.zip](https://github.com/anonymix007/ExtA2DP/files/12643860/mi10t.zip)

**Comment by matthew777777** [comment]
Shalom,
Thanks for quick action but it still doesn't work screen shot below

![Screenshot_20230918-072721_ExtA2DP](https://github.com/anonymix007/ExtA2DP/assets/134064721/5b163d28-058a-49c6-a2dd-66e7158f9de7)

**Comment by anonymix007** [comment]
It's debug information, there shouldn't be any other text here.
Reboot and attach logs when you open dev settings and turn on Bluetooth.

**Comment by matthew777777** [comment]
Shalom Hi,
It still doesn't work and below are two logs 
[logcat--2023-09-19--15-46.log](https://github.com/anonymix007/ExtA2DP/files/12660992/logcat--2023-09-19--15-46.log)
[logcat--2023-09-19--15-24.log](https://github.com/anonymix007/ExtA2DP/files/12660993/logcat--2023-09-19--15-24.log)
Shalom Shalom

**Comment by matthew777777** [comment]
> These logs don't contain information I asked for. First make sure you installed everything exactly like README suggests, when turn off Bluetooth and force stop Bluetooth and Settings system apps. And only then record logs. Oh, and besides, "doesn't work" is not a proper issue description. What exactly doesn't work? You're seem to be using KernelSU. I never tested it, so try Magisk.

Okay I will try using magisk and doing as you said and will send logs.
Yeah I could describe it with more information like always we learn every day.
Shalom Shalom

**Comment by matthew777777** [comment]
> These logs don't contain information I asked for. First make sure you installed everything exactly like README suggests, when turn off Bluetooth and force stop Bluetooth and Settings system apps. And only then record logs. Oh, and besides, "doesn't work" is not a proper issue description. What exactly doesn't work? You're seem to be using KernelSU. I never tested it, so try Magisk.

I did exactly as you said ( Magisk 26.3 + LSPosed-v1.9.1-6997-zygisk + module above + all readme and logs as you said)
Logs below ( I hope it has any useful information)
Thanks for your help.
[2023-09-19-19-16-00.txt](https://github.com/anonymix007/ExtA2DP/files/12664741/2023-09-19-19-16-00.txt)
[2023-09-19-19-13-03.txt](https://github.com/anonymix007/ExtA2DP/files/12664742/2023-09-19-19-13-03.txt)
[2023-09-19-19-07-58-log.txt](https://github.com/anonymix007/ExtA2DP/files/12664744/2023-09-19-19-07-58-log.txt)

**Comment by matthew777777** [comment]
One more log 
[log.txt](https://github.com/anonymix007/ExtA2DP/files/12664759/log.txt)
( sorry if is too much I'm not good with logs )

**Comment by anonymix007** [comment]
Try using debug version of LSPosed. Unfortunately, I can't do much about this currently, see corresponding [LSPosed issue](https://github.com/LSPosed/LSPosed/issues/2759):
```console
09-19 19:11:43.050 E/LSPosedContext(9355): java.lang.NoSuchFieldException: No field apk in class Ll0; (declaration of 'l0' appears in Anonymous-DexFile@1393342585)
```
I don't see any issues with Bluetooth, have you tried actually listening to some music?

**Comment by matthew777777** [comment]
> Try using debug version of LSPosed. Unfortunately, I can't do much about this currently, see corresponding [LSPosed issue](https://github.com/LSPosed/LSPosed/issues/2759):
> 
> ```
> 09-19 19:11:43.050 E/LSPosedContext(9355): java.lang.NoSuchFieldException: No field apk in class Ll0; (declaration of 'l0' appears in Anonymous-DexFile@1393342585)
> ```
> 
> I don't see any issues with Bluetooth, have you tried actually listening to some music?

I didn't but connected earbuds and getting only aac and sbc available.
I will try soon and let you know

**Comment by anonymix007** [comment]
Available where? In developer options? Then it's fine and completely expected. Only AAC and SBC are available (note that none of them is selected, that means that none of them are being used):
![Screenshot_2023-09-20-00-27-24-392](https://github.com/anonymix007/ExtA2DP/assets/48598263/1499cb49-4402-46da-bd53-7d36be7426bf)
But LHDC still works:
![Screenshot_2023-09-20-00-29-03-218](https://github.com/anonymix007/ExtA2DP/assets/48598263/2a53576b-829c-48dd-8bcc-85ad995f9779)

**Comment by matthew777777** [comment]
> Available where? In developer options? Then it's fine and completely expected. Only AAC and SBC are available (note that none of them is selected, that means that none of them are being used): ![Screenshot_2023-09-20-00-27-24-392](https://user-images.githubusercontent.com/48598263/269099653-1499cb49-4402-46da-bd53-7d36be7426bf.jpg) But LHDC still works: ![Screenshot_2023-09-20-00-29-03-218](https://user-images.githubusercontent.com/48598263/269099817-2a53576b-829c-48dd-8bcc-85ad995f9779.jpg)

Yes In dev option but app you showing above doesn't load 😔 so I don't know if that works or not.

**Comment by anonymix007** [comment]
I guess it should be solved now...
Try latest release and latest ci debug version of LSPosed.
> app you showing above doesn't load

What do you mean by that? It's available in Google Play.

**Comment by matthew777777** [comment]
> I guess it should be solved now... Try latest release and latest ci debug version of LSPosed. **UPD** Now release version should work as well, but it's not recommended.
> 
> > app you showing above doesn't load
> 
> What do you mean by that? It's available in Google Play.

Thanks a lot sorry didn't know that.
It works fine.
Thank you for all the help and your time.
I wish you the best Shalom Shalom
