### ISSUE TITLE
Doesn't work on pixel 4.

### ISSUE THREAD

**Issue by MOneK292** [anonymix007/ExtA2DP#8]
Is pixel 4 support possible? Installed, but when selected, everything is gray. Pixel Experience A13+ firmware.

**Comment by anonymix007** [comment]
> Is pixel 4 support possible?

Yes.
> Pixel Experience A13+ firmware.

Not CLO, so
> Installed, but when selected, everything is gray.

this is expected.

**Comment by MOneK292** [comment]
That is, you can install another firmware and it will work?

**Comment by anonymix007** [comment]
Answer is "yes" to both. But there are no CLO ROMs for Pixel 4.
And to make such module you'll need to build libbluetooth_jni.so and replace it instead of libbluetooth_qti.so (which is what ExtA2DP currently doing)
